api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: true
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: false
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--deepseekr1ai
        value: '{{ .Env.DEEPSEEKR1__CONNECTIONSTRING }}'
      - name: deploymentname
        value: '{{ .Env.DEEPSEEKR1_DEPLOYMENT_NAME }}'    
      - name: endpoint
        value: '{{ .Env.DEEPSEEKR1_ENDPOINT }}'
      - name: tenantid
        value: '{{ .Env.DEEPSEEKR1_TENANT_ID }}'
  template:
    containers:
      - image: {{ .Image }}
        name: blazorchatdeepseekr1
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: ConnectionStrings__deepseekr1ai
            secretRef: connectionstrings--deepseekr1ai
          - name: deploymentname
            secretRef: deploymentname
          - name: endpoint
            secretRef: endpoint
          - name: tenantid
            secretRef: tenantid
    scale:
      minReplicas: 1
tags:
  azd-service-name: blazorchatdeepseekr1
  aspire-resource-name: blazorchatdeepseekr1
